baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Main hugo.toml overites this file'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


# -- Markup --
# These settings are required for the theme to function.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4

  [pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'
  paginate = 3